<?php
namespace webaze\modulelp;

use yii\base\BootstrapInterface;
use yii\web\GroupUrlRule;

class Module extends \yii\base\Module implements BootstrapInterface
{
    public $id = 'modulelp';


    public function init()
    {
        $this->controllerNamespace = 'webaze\modulelp\controllers';
        $this->viewPath = __DIR__ . '/views';

        parent::init(); // TODO: Change the autogenerated stub
    }


    public function bootstrap($app)
    {
        $this->controllerNamespace = 'webaze\modulelp\controllers';
        $this->viewPath = __DIR__ . '/views';

        $app->urlManager->addRules([
            new GroupUrlRule([
                'prefix' => 'modulelp',
                'rules' => [
                    // Your module's controller routes here...
                ],
            ]),
        ]);

//
//        $configUrlRule = [
//            //'prefix' => 'ops',
//            'routePrefix' => 'modulelp',
//            'rules' => require(__DIR__ . '/config/url.php'),
//        ];
//
//        $app->getUrlManager()->rules[] = (new GroupUrlRule($configUrlRule));
    }
}